spring:
  application:
    name: zk-backend

logging:
  level:
    root: INFO
    com.sommerph.zkbackend: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html

keys:
  curve: secp256r1

  issuer:
    algorithm: ES256
    source: static
    key-id: issuer-001
    fixed-private: "46012408107196755923706193987463047920137073659172279781266729514345066549384"
    fixed-public-x: "66432692286261411630769223098970693805397596870633670159153355502222145619968"
    fixed-public-y: "63182586149833488067701290985084360701345487374231728189741684364091950142361"

  credential:
    binding:
      algorithm: ES256
      generate-per-credential: false

eudi:
  wallet:
    registry:
      type: json
    storage:
      path: data/eudi-wallets
  credential:
    claims:
      - documentNumber
      - name
      - givenName
      - dateOfBirth
      - nationality

blockchain:
  wallet:
    registry:
      type: json
    storage:
      path: data/blockchain-wallets

proof:
  preparation:
    registry:
      type: json
    storage:
      path: data/proof-preparation
  extended:
    computeOffsets: true