[package]
name = "zk-recursive-nova"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
nova-scotia = "0.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nova-snark = "0.23"
ff = "0.13"
