[package]
name    = "zk-recursive"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2       = { git = "https://github.com/sommer-ph/plonky2", branch = "main" }

sha2 = "0.10"
rand = "0.9.1"
num-bigint = "0.4"
num-traits = "0.2"
once_cell = "1.19"